start linux 3.12 branch

diff --git a/debian/scripts/dfsg-prune b/debian/scripts/dfsg-prune
--- a/debian/scripts/dfsg-prune
+++ b/debian/scripts/dfsg-prune
@@ -1,9 +1,12 @@
 #!/bin/bash
 set -e
 
-#http_proxy=http://proxyserver.lan:3128
-#ftp_proxy=http://proxyserver.lan:3128
-#export http_proxy ftp_proxy
+if wget -S http://proxyserver.lan.:3128 2>&1 | grep -q Server\:\ squid; then
+	http_proxy=http://proxyserver.lan:3128
+	https_proxy=http://proxyserver.lan:3128
+	ftp_proxy=http://proxyserver.lan:3128
+	export http_proxy https_proxy ftp_proxy
+fi
 
 VERSION_DEBIAN="${1}"
 VERSION="${2}"
@@ -15,6 +18,22 @@ K_TEMP="${K_TEMP%%-*}"
 K_VERSION="$(echo ${K_TEMP} | cut -d\. -f1)"
 K_PATCHLEVEL="$(echo ${K_TEMP} | cut -d\. -f2)"
 K_SUBLEVEL="$(echo ${K_TEMP} | cut -d\. -f3)"
+
+if [ -x "$(which pixz)" ]; then
+	case $(uname -m) in
+		i[0-9]86|x86_64)
+			XZ="pixz -8"
+			;;
+		*)
+			# ease up compression on, typically, slow architectures
+			XZ="pixz -7"
+			;;
+	esac
+elif [ -x "$(which xz)" ]; then
+	XZ="xz -6"
+else
+	echo "ERROR: neither xz nor pixz found in the PATH" >&2
+fi
 
 case "${VERSION}" in
 	2\.*)
@@ -30,34 +49,34 @@ esac
 RC_VER="${VERSION#*\~}"
 [ "x${VERSION%\~*}" = "x${RC_VER}" ] && RC_VER=""
 
-TMP_DIR="$(mktemp -d -p /tmp linux-siduction.XXXXXX)"
+TMP_DIR="$(mktemp -d --tmpdir linux-siduction.XXXXXX)"
 pushd "${TMP_DIR}"
 	if [ -z "$RC_VER" ]; then
 		# stable kernel
-		UP_TARBALL="linux-${MAJOR_VER}.tar.bz2"
-		wget -Nc "http://www.kernel.org/pub/linux/kernel/v${K_VERSION}.${K_PATCHLEVEL_SYM}/${UP_TARBALL}"
+		UP_TARBALL="linux-${MAJOR_VER}.tar.xz"
+		wget -Nc "ftp://ftp.kernel.org/pub/linux/kernel/v${K_VERSION}.${K_PATCHLEVEL_SYM}/${UP_TARBALL}"
 
 		if [ -n "${K_SUBLEVEL}" ]; then
-			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}.${K_SUBLEVEL}.orig.tar.bz2"
+			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}.${K_SUBLEVEL}.orig.tar.xz"
 		else
-			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}.orig.tar.bz2"
+			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}.orig.tar.xz"
 		fi
 	else
 		# rc kernel
-		UP_TARBALL="linux-${MAJOR_VER}-${RC_VER}.tar.bz2"
-		#wget -Nc "http://www.kernel.org/pub/linux/kernel/v${K_VERSION}.${K_PATCHLEVEL_SYM}/testing/${UP_TARBALL}"
-		cp /home/towo/testkernel/private/${UP_TARBALL} ./
+		UP_TARBALL="linux-${MAJOR_VER}-${RC_VER}.tar.xz"
+		wget -Nc "ftp://ftp.kernel.org/pub/linux/kernel/v${K_VERSION}.${K_PATCHLEVEL_SYM}/testing/${UP_TARBALL}"
+
 		if [ -n "${K_SUBLEVEL}" ]; then
-			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}.${K_SUBLEVEL}~${RC_VER}.orig.tar.bz2"
+			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}.${K_SUBLEVEL}~${RC_VER}.orig.tar.xz"
 		else
-			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}~${RC_VER}.orig.tar.bz2"
+			ORIG_TARBALL="linux-siduction_${K_VERSION}.${K_PATCHLEVEL}~${RC_VER}.orig.tar.xz"
 		fi
 	fi
 popd >/dev/null 2>&1
 
 mkdir "${TMP_DIR}/linux-${VERSION}"
 pushd "${TMP_DIR}/linux-${VERSION}" >/dev/null 2>&1
-	tar --strip 1 -xjf "${TMP_DIR}/${UP_TARBALL}"
+	tar --strip 1 -xJf "${TMP_DIR}/${UP_TARBALL}"
 	rm "${TMP_DIR}/${UP_TARBALL}"
 
 	# remove shipped firmware images
@@ -78,6 +97,7 @@ pushd "${TMP_DIR}/linux-${VERSION}" >/dev/null 2>&1
 		drivers/staging/ft1000/ft1000-pcmcia/boot.h \
 		drivers/staging/ft1000/ft1000-*/*.img \
 		drivers/staging/keucr/init.h \
+		drivers/staging/rtl8188eu/hal/Hal8188EFWImg_CE.c \
 		drivers/staging/wlags49_h2/ap_h2.c \
 		drivers/staging/wlags49_h2/ap_h25.c \
 		drivers/staging/wlags49_h2/sta_h2.c \
@@ -102,8 +122,8 @@ pushd "${TMP_DIR}" >/dev/null 2>&1
 		--numeric-owner \
 		--owner=0 \
 		--group=0 \
-		-cjf "${TMP_DIR}/${ORIG_TARBALL}" \
-			"linux-${VERSION}"
+		-cf - "linux-${VERSION}" | \
+			${XZ} >"${TMP_DIR}/${ORIG_TARBALL}"
 
 	rm -rf ${TMP_DIR}/linux-${VERSION}
 popd >/dev/null 2>&1
